# .github/workflows/linting.yaml

name: ruff

on:
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pdm install

      - name: Run ruff linter
        run: pdm lint
